token:
  expiration_time: 86400000
  secret: '{cipher}AQB+YRUKgmXGiVVhLOCaEbxar0SgREJ3L+dKukvJskAj/LJLQ9+1kuEJdEt5OWI6zW9uwOPgI7o4OuqNGJ74r7TKL6YLjaxjX3S7lKfasj7pqDNiIjSBye62yJxiaV3cRKfKOGoh7SCrrzYWfeKMY4yEsqcIZvlM307jh2vMYc2FMn05LrBLw1YftnXC9GeF2SHI9chGfIkTPdrxqN8HIbFzyw6M1eFRjh/GyKh1wNgdk9CVziyfvDH7NygdaLT3XaKIsEsYOKqvWM5HuSSHzu71dHaqQylpAzVvJFQ13rXcoOpjzEp5YaIirA5hH4wD4bgMtw5lnvMA0RhpWcP1yinZHgxiz35mMAbjNdTYa+0ZR/Y53h1jEn+/M1eQLKtqwTk='

gateway:
  ip: 192.168.0.8

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQActCUhJUaLBD8x+fxQvg/C2IL56eNejV9F4QqMxpyQldRHTtyzWjpPekT3wvwx4yi78GnxoDjYYMYg7n/1naRMlE+2Ev59TM+EYDR/stgNNjvCzQaNYIHBO7xT2eydvSntAg0fnk30z+bbP42G+Ciq+614yANUzUzRRLLomJhrTg1Vjt//d8V4XYWUwxeGtGk0NROgHzRP1VAncUhgz1z8X369MuICf8pM6blr0FeSTcOhzgj6mI97IDezJBAxk3xo3apqjm2rMiiHCjHqHn9sTHr0Ddwa7tarSdtY3k1N5DmJxjDLWpkeLS6+ds0t20uemBAzXhtDOvu07z0oDeyFQyUrGfgbgvdmQOrLwpxuLf9yxuHR9nh27rT2aovxf08='
    #'{cipher}' 라고하면 암호화된 텍스트로 인식하여 config service에서 encrypt key 값으로 복호화 함