token:
  expiration_time: 86400000
  secret: user_service_token

gateway:
  ip: 192.168.0.8

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234